/*
 * Copyright (C) 2016 - Niklas Baudy, Ruben Gees, Mario Đanić and contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.vanniktech.emoji.facebook.category;

import com.vanniktech.emoji.facebook.FacebookEmoji;

final class ObjectsCategoryChunk0 {
  @SuppressWarnings("PMD.ExcessiveMethodLength") static FacebookEmoji[] get() {
    return new FacebookEmoji[] {
      new FacebookEmoji(0x1F453, new String[]{"eyeglasses"}, 13, 28, false),
      new FacebookEmoji(new int[] { 0x1F576, 0xFE0F }, new String[]{"dark_sunglasses"}, 31, 53, false),
      new FacebookEmoji(0x1F97D, new String[]{"goggles"}, 44, 29, false),
      new FacebookEmoji(0x1F97C, new String[]{"lab_coat"}, 44, 28, false),
      new FacebookEmoji(0x1F9BA, new String[]{"safety_vest"}, 46, 10, false),
      new FacebookEmoji(0x1F454, new String[]{"necktie"}, 13, 29, false),
      new FacebookEmoji(0x1F455, new String[]{"shirt", "tshirt"}, 13, 30, false),
      new FacebookEmoji(0x1F456, new String[]{"jeans"}, 13, 31, false),
      new FacebookEmoji(0x1F9E3, new String[]{"scarf"}, 53, 39, false),
      new FacebookEmoji(0x1F9E4, new String[]{"gloves"}, 53, 40, false),
      new FacebookEmoji(0x1F9E5, new String[]{"coat"}, 53, 41, false),
      new FacebookEmoji(0x1F9E6, new String[]{"socks"}, 53, 42, false),
      new FacebookEmoji(0x1F457, new String[]{"dress"}, 13, 32, false),
      new FacebookEmoji(0x1F458, new String[]{"kimono"}, 13, 33, false),
      new FacebookEmoji(0x1F97B, new String[]{"sari"}, 44, 27, false),
      new FacebookEmoji(0x1FA71, new String[]{"one-piece_swimsuit"}, 54, 9, false),
      new FacebookEmoji(0x1FA72, new String[]{"briefs"}, 54, 10, false),
      new FacebookEmoji(0x1FA73, new String[]{"shorts"}, 54, 11, false),
      new FacebookEmoji(0x1F459, new String[]{"bikini"}, 13, 34, false),
      new FacebookEmoji(0x1F45A, new String[]{"womans_clothes"}, 13, 35, false),
      new FacebookEmoji(0x1F45B, new String[]{"purse"}, 13, 36, false),
      new FacebookEmoji(0x1F45C, new String[]{"handbag"}, 13, 37, false),
      new FacebookEmoji(0x1F45D, new String[]{"pouch"}, 13, 38, false),
      new FacebookEmoji(new int[] { 0x1F6CD, 0xFE0F }, new String[]{"shopping_bags"}, 38, 37, false),
      new FacebookEmoji(0x1F392, new String[]{"school_satchel"}, 7, 33, false),
      new FacebookEmoji(0x1FA74, new String[]{"thong_sandal"}, 54, 12, false),
      new FacebookEmoji(0x1F45E, new String[]{"mans_shoe", "shoe"}, 13, 39, false),
      new FacebookEmoji(0x1F45F, new String[]{"athletic_shoe"}, 13, 40, false),
      new FacebookEmoji(0x1F97E, new String[]{"hiking_boot"}, 44, 30, false),
      new FacebookEmoji(0x1F97F, new String[]{"womans_flat_shoe"}, 44, 31, false),
      new FacebookEmoji(0x1F460, new String[]{"high_heel"}, 13, 41, false),
      new FacebookEmoji(0x1F461, new String[]{"sandal"}, 13, 42, false),
      new FacebookEmoji(0x1FA70, new String[]{"ballet_shoes"}, 54, 8, false),
      new FacebookEmoji(0x1F462, new String[]{"boot"}, 13, 43, false),
      new FacebookEmoji(0x1F451, new String[]{"crown"}, 13, 26, false),
      new FacebookEmoji(0x1F452, new String[]{"womans_hat"}, 13, 27, false),
      new FacebookEmoji(0x1F3A9, new String[]{"tophat"}, 7, 51, false),
      new FacebookEmoji(0x1F393, new String[]{"mortar_board"}, 7, 34, false),
      new FacebookEmoji(0x1F9E2, new String[]{"billed_cap"}, 53, 38, false),
      new FacebookEmoji(0x1FA96, new String[]{"military_helmet"}, 54, 29, false),
      new FacebookEmoji(new int[] { 0x26D1, 0xFE0F }, new String[]{"helmet_with_white_cross"}, 56, 56, false),
      new FacebookEmoji(0x1F4FF, new String[]{"prayer_beads"}, 29, 53, false),
      new FacebookEmoji(0x1F484, new String[]{"lipstick"}, 26, 17, false),
      new FacebookEmoji(0x1F48D, new String[]{"ring"}, 27, 5, false),
      new FacebookEmoji(0x1F48E, new String[]{"gem"}, 27, 6, false),
      new FacebookEmoji(0x1F507, new String[]{"mute"}, 30, 1, false),
      new FacebookEmoji(0x1F508, new String[]{"speaker"}, 30, 2, false),
      new FacebookEmoji(0x1F509, new String[]{"sound"}, 30, 3, false),
      new FacebookEmoji(0x1F50A, new String[]{"loud_sound"}, 30, 4, false),
      new FacebookEmoji(0x1F4E2, new String[]{"loudspeaker"}, 29, 25, false),
      new FacebookEmoji(0x1F4E3, new String[]{"mega"}, 29, 26, false),
      new FacebookEmoji(0x1F4EF, new String[]{"postal_horn"}, 29, 38, false),
      new FacebookEmoji(0x1F514, new String[]{"bell"}, 30, 14, false),
      new FacebookEmoji(0x1F515, new String[]{"no_bell"}, 30, 15, false),
      new FacebookEmoji(0x1F3BC, new String[]{"musical_score"}, 8, 10, false),
      new FacebookEmoji(0x1F3B5, new String[]{"musical_note"}, 8, 3, false),
      new FacebookEmoji(0x1F3B6, new String[]{"notes"}, 8, 4, false),
      new FacebookEmoji(new int[] { 0x1F399, 0xFE0F }, new String[]{"studio_microphone"}, 7, 37, false),
      new FacebookEmoji(new int[] { 0x1F39A, 0xFE0F }, new String[]{"level_slider"}, 7, 38, false),
      new FacebookEmoji(new int[] { 0x1F39B, 0xFE0F }, new String[]{"control_knobs"}, 7, 39, false),
      new FacebookEmoji(0x1F3A4, new String[]{"microphone"}, 7, 46, false),
      new FacebookEmoji(0x1F3A7, new String[]{"headphones"}, 7, 49, false),
      new FacebookEmoji(0x1F4FB, new String[]{"radio"}, 29, 50, false),
      new FacebookEmoji(0x1F3B7, new String[]{"saxophone"}, 8, 5, false),
      new FacebookEmoji(0x1FA97, new String[]{"accordion"}, 54, 30, false),
      new FacebookEmoji(0x1F3B8, new String[]{"guitar"}, 8, 6, false),
      new FacebookEmoji(0x1F3B9, new String[]{"musical_keyboard"}, 8, 7, false),
      new FacebookEmoji(0x1F3BA, new String[]{"trumpet"}, 8, 8, false),
      new FacebookEmoji(0x1F3BB, new String[]{"violin"}, 8, 9, false),
      new FacebookEmoji(0x1FA95, new String[]{"banjo"}, 54, 28, false),
      new FacebookEmoji(0x1F941, new String[]{"drum_with_drumsticks"}, 43, 26, false),
      new FacebookEmoji(0x1FA98, new String[]{"long_drum"}, 54, 31, false),
      new FacebookEmoji(0x1F4F1, new String[]{"iphone"}, 29, 40, false),
      new FacebookEmoji(0x1F4F2, new String[]{"calling"}, 29, 41, false),
      new FacebookEmoji(new int[] { 0x260E, 0xFE0F }, new String[]{"phone", "telephone"}, 55, 49, false),
      new FacebookEmoji(0x1F4DE, new String[]{"telephone_receiver"}, 29, 21, false),
      new FacebookEmoji(0x1F4DF, new String[]{"pager"}, 29, 22, false),
      new FacebookEmoji(0x1F4E0, new String[]{"fax"}, 29, 23, false),
      new FacebookEmoji(0x1F50B, new String[]{"battery"}, 30, 5, false),
      new FacebookEmoji(0x1F50C, new String[]{"electric_plug"}, 30, 6, false),
      new FacebookEmoji(0x1F4BB, new String[]{"computer"}, 28, 46, false),
      new FacebookEmoji(new int[] { 0x1F5A5, 0xFE0F }, new String[]{"desktop_computer"}, 32, 27, false),
      new FacebookEmoji(new int[] { 0x1F5A8, 0xFE0F }, new String[]{"printer"}, 32, 28, false),
      new FacebookEmoji(new int[] { 0x2328, 0xFE0F }, new String[]{"keyboard"}, 55, 19, false),
      new FacebookEmoji(new int[] { 0x1F5B1, 0xFE0F }, new String[]{"three_button_mouse"}, 32, 29, false),
      new FacebookEmoji(new int[] { 0x1F5B2, 0xFE0F }, new String[]{"trackball"}, 32, 30, false),
      new FacebookEmoji(0x1F4BD, new String[]{"minidisc"}, 28, 48, false),
      new FacebookEmoji(0x1F4BE, new String[]{"floppy_disk"}, 28, 49, false),
      new FacebookEmoji(0x1F4BF, new String[]{"cd"}, 28, 50, false),
      new FacebookEmoji(0x1F4C0, new String[]{"dvd"}, 28, 51, false),
      new FacebookEmoji(0x1F9EE, new String[]{"abacus"}, 53, 50, false),
      new FacebookEmoji(0x1F3A5, new String[]{"movie_camera"}, 7, 47, false),
      new FacebookEmoji(new int[] { 0x1F39E, 0xFE0F }, new String[]{"film_frames"}, 7, 40, false),
      new FacebookEmoji(new int[] { 0x1F4FD, 0xFE0F }, new String[]{"film_projector"}, 29, 52, false),
      new FacebookEmoji(0x1F3AC, new String[]{"clapper"}, 7, 54, false),
      new FacebookEmoji(0x1F4FA, new String[]{"tv"}, 29, 49, false),
      new FacebookEmoji(0x1F4F7, new String[]{"camera"}, 29, 46, false),
      new FacebookEmoji(0x1F4F8, new String[]{"camera_with_flash"}, 29, 47, false),
      new FacebookEmoji(0x1F4F9, new String[]{"video_camera"}, 29, 48, false),
      new FacebookEmoji(0x1F4FC, new String[]{"vhs"}, 29, 51, false),
      new FacebookEmoji(0x1F50D, new String[]{"mag"}, 30, 7, false),
      new FacebookEmoji(0x1F50E, new String[]{"mag_right"}, 30, 8, false),
      new FacebookEmoji(new int[] { 0x1F56F, 0xFE0F }, new String[]{"candle"}, 31, 26, false),
      new FacebookEmoji(0x1F4A1, new String[]{"bulb"}, 28, 15, false),
      new FacebookEmoji(0x1F526, new String[]{"flashlight"}, 30, 32, false),
      new FacebookEmoji(0x1F3EE, new String[]{"izakaya_lantern", "lantern"}, 10, 35, false),
      new FacebookEmoji(0x1FA94, new String[]{"diya_lamp"}, 54, 27, false),
      new FacebookEmoji(0x1F4D4, new String[]{"notebook_with_decorative_cover"}, 29, 11, false),
      new FacebookEmoji(0x1F4D5, new String[]{"closed_book"}, 29, 12, false),
      new FacebookEmoji(0x1F4D6, new String[]{"book", "open_book"}, 29, 13, false),
      new FacebookEmoji(0x1F4D7, new String[]{"green_book"}, 29, 14, false),
      new FacebookEmoji(0x1F4D8, new String[]{"blue_book"}, 29, 15, false),
      new FacebookEmoji(0x1F4D9, new String[]{"orange_book"}, 29, 16, false),
      new FacebookEmoji(0x1F4DA, new String[]{"books"}, 29, 17, false),
      new FacebookEmoji(0x1F4D3, new String[]{"notebook"}, 29, 10, false),
      new FacebookEmoji(0x1F4D2, new String[]{"ledger"}, 29, 9, false),
      new FacebookEmoji(0x1F4C3, new String[]{"page_with_curl"}, 28, 54, false),
      new FacebookEmoji(0x1F4DC, new String[]{"scroll"}, 29, 19, false),
      new FacebookEmoji(0x1F4C4, new String[]{"page_facing_up"}, 28, 55, false),
      new FacebookEmoji(0x1F4F0, new String[]{"newspaper"}, 29, 39, false),
      new FacebookEmoji(new int[] { 0x1F5DE, 0xFE0F }, new String[]{"rolled_up_newspaper"}, 32, 40, false),
      new FacebookEmoji(0x1F4D1, new String[]{"bookmark_tabs"}, 29, 8, false),
      new FacebookEmoji(0x1F516, new String[]{"bookmark"}, 30, 16, false),
      new FacebookEmoji(new int[] { 0x1F3F7, 0xFE0F }, new String[]{"label"}, 10, 47, false),
      new FacebookEmoji(0x1F4B0, new String[]{"moneybag"}, 28, 35, false),
      new FacebookEmoji(0x1FA99, new String[]{"coin"}, 54, 32, false),
      new FacebookEmoji(0x1F4B4, new String[]{"yen"}, 28, 39, false),
      new FacebookEmoji(0x1F4B5, new String[]{"dollar"}, 28, 40, false),
      new FacebookEmoji(0x1F4B6, new String[]{"euro"}, 28, 41, false),
      new FacebookEmoji(0x1F4B7, new String[]{"pound"}, 28, 42, false),
      new FacebookEmoji(0x1F4B8, new String[]{"money_with_wings"}, 28, 43, false),
      new FacebookEmoji(0x1F4B3, new String[]{"credit_card"}, 28, 38, false),
      new FacebookEmoji(0x1F9FE, new String[]{"receipt"}, 54, 6, false),
      new FacebookEmoji(0x1F4B9, new String[]{"chart"}, 28, 44, false),
      new FacebookEmoji(new int[] { 0x2709, 0xFE0F }, new String[]{"email", "envelope"}, 57, 32, false),
      new FacebookEmoji(0x1F4E7, new String[]{"e-mail"}, 29, 30, false),
      new FacebookEmoji(0x1F4E8, new String[]{"incoming_envelope"}, 29, 31, false),
      new FacebookEmoji(0x1F4E9, new String[]{"envelope_with_arrow"}, 29, 32, false),
      new FacebookEmoji(0x1F4E4, new String[]{"outbox_tray"}, 29, 27, false),
      new FacebookEmoji(0x1F4E5, new String[]{"inbox_tray"}, 29, 28, false),
      new FacebookEmoji(0x1F4E6, new String[]{"package"}, 29, 29, false),
      new FacebookEmoji(0x1F4EB, new String[]{"mailbox"}, 29, 34, false),
      new FacebookEmoji(0x1F4EA, new String[]{"mailbox_closed"}, 29, 33, false),
      new FacebookEmoji(0x1F4EC, new String[]{"mailbox_with_mail"}, 29, 35, false),
      new FacebookEmoji(0x1F4ED, new String[]{"mailbox_with_no_mail"}, 29, 36, false),
      new FacebookEmoji(0x1F4EE, new String[]{"postbox"}, 29, 37, false),
      new FacebookEmoji(new int[] { 0x1F5F3, 0xFE0F }, new String[]{"ballot_box_with_ballot"}, 32, 45, false),
      new FacebookEmoji(new int[] { 0x270F, 0xFE0F }, new String[]{"pencil2"}, 57, 57, false),
      new FacebookEmoji(new int[] { 0x2712, 0xFE0F }, new String[]{"black_nib"}, 57, 58, false),
      new FacebookEmoji(new int[] { 0x1F58B, 0xFE0F }, new String[]{"lower_left_fountain_pen"}, 32, 5, false),
      new FacebookEmoji(new int[] { 0x1F58A, 0xFE0F }, new String[]{"lower_left_ballpoint_pen"}, 32, 4, false),
      new FacebookEmoji(new int[] { 0x1F58C, 0xFE0F }, new String[]{"lower_left_paintbrush"}, 32, 6, false),
      new FacebookEmoji(new int[] { 0x1F58D, 0xFE0F }, new String[]{"lower_left_crayon"}, 32, 7, false),
      new FacebookEmoji(0x1F4DD, new String[]{"memo", "pencil"}, 29, 20, false),
      new FacebookEmoji(0x1F4BC, new String[]{"briefcase"}, 28, 47, false),
      new FacebookEmoji(0x1F4C1, new String[]{"file_folder"}, 28, 52, false),
      new FacebookEmoji(0x1F4C2, new String[]{"open_file_folder"}, 28, 53, false),
      new FacebookEmoji(new int[] { 0x1F5C2, 0xFE0F }, new String[]{"card_index_dividers"}, 32, 32, false),
      new FacebookEmoji(0x1F4C5, new String[]{"date"}, 28, 56, false),
      new FacebookEmoji(0x1F4C6, new String[]{"calendar"}, 28, 57, false),
      new FacebookEmoji(new int[] { 0x1F5D2, 0xFE0F }, new String[]{"spiral_note_pad"}, 32, 36, false),
      new FacebookEmoji(new int[] { 0x1F5D3, 0xFE0F }, new String[]{"spiral_calendar_pad"}, 32, 37, false),
      new FacebookEmoji(0x1F4C7, new String[]{"card_index"}, 28, 58, false),
      new FacebookEmoji(0x1F4C8, new String[]{"chart_with_upwards_trend"}, 28, 59, false),
      new FacebookEmoji(0x1F4C9, new String[]{"chart_with_downwards_trend"}, 29, 0, false),
      new FacebookEmoji(0x1F4CA, new String[]{"bar_chart"}, 29, 1, false),
      new FacebookEmoji(0x1F4CB, new String[]{"clipboard"}, 29, 2, false),
      new FacebookEmoji(0x1F4CC, new String[]{"pushpin"}, 29, 3, false),
      new FacebookEmoji(0x1F4CD, new String[]{"round_pushpin"}, 29, 4, false),
      new FacebookEmoji(0x1F4CE, new String[]{"paperclip"}, 29, 5, false),
      new FacebookEmoji(new int[] { 0x1F587, 0xFE0F }, new String[]{"linked_paperclips"}, 32, 3, false),
      new FacebookEmoji(0x1F4CF, new String[]{"straight_ruler"}, 29, 6, false),
      new FacebookEmoji(0x1F4D0, new String[]{"triangular_ruler"}, 29, 7, false),
      new FacebookEmoji(new int[] { 0x2702, 0xFE0F }, new String[]{"scissors"}, 57, 29, false),
      new FacebookEmoji(new int[] { 0x1F5C3, 0xFE0F }, new String[]{"card_file_box"}, 32, 33, false),
      new FacebookEmoji(new int[] { 0x1F5C4, 0xFE0F }, new String[]{"file_cabinet"}, 32, 34, false),
      new FacebookEmoji(new int[] { 0x1F5D1, 0xFE0F }, new String[]{"wastebasket"}, 32, 35, false),
      new FacebookEmoji(0x1F512, new String[]{"lock"}, 30, 12, false),
      new FacebookEmoji(0x1F513, new String[]{"unlock"}, 30, 13, false),
      new FacebookEmoji(0x1F50F, new String[]{"lock_with_ink_pen"}, 30, 9, false),
      new FacebookEmoji(0x1F510, new String[]{"closed_lock_with_key"}, 30, 10, false),
      new FacebookEmoji(0x1F511, new String[]{"key"}, 30, 11, false),
      new FacebookEmoji(new int[] { 0x1F5DD, 0xFE0F }, new String[]{"old_key"}, 32, 39, false),
      new FacebookEmoji(0x1F528, new String[]{"hammer"}, 30, 34, false),
      new FacebookEmoji(0x1FA93, new String[]{"axe"}, 54, 26, false),
      new FacebookEmoji(new int[] { 0x26CF, 0xFE0F }, new String[]{"pick"}, 56, 55, false),
      new FacebookEmoji(new int[] { 0x2692, 0xFE0F }, new String[]{"hammer_and_pick"}, 56, 33, false),
      new FacebookEmoji(new int[] { 0x1F6E0, 0xFE0F }, new String[]{"hammer_and_wrench"}, 38, 46, false),
      new FacebookEmoji(new int[] { 0x1F5E1, 0xFE0F }, new String[]{"dagger_knife"}, 32, 41, false),
      new FacebookEmoji(new int[] { 0x2694, 0xFE0F }, new String[]{"crossed_swords"}, 56, 35, false),
      new FacebookEmoji(0x1F52B, new String[]{"gun"}, 30, 37, false),
      new FacebookEmoji(0x1FA83, new String[]{"boomerang"}, 54, 19, false),
      new FacebookEmoji(0x1F3F9, new String[]{"bow_and_arrow"}, 10, 49, false),
      new FacebookEmoji(new int[] { 0x1F6E1, 0xFE0F }, new String[]{"shield"}, 38, 47, false),
      new FacebookEmoji(0x1FA9A, new String[]{"carpentry_saw"}, 54, 33, false),
      new FacebookEmoji(0x1F527, new String[]{"wrench"}, 30, 33, false),
      new FacebookEmoji(0x1FA9B, new String[]{"screwdriver"}, 54, 34, false),
      new FacebookEmoji(0x1F529, new String[]{"nut_and_bolt"}, 30, 35, false),
      new FacebookEmoji(new int[] { 0x2699, 0xFE0F }, new String[]{"gear"}, 56, 39, false),
      new FacebookEmoji(new int[] { 0x1F5DC, 0xFE0F }, new String[]{"compression"}, 32, 38, false),
      new FacebookEmoji(new int[] { 0x2696, 0xFE0F }, new String[]{"scales"}, 56, 37, false),
      new FacebookEmoji(0x1F9AF, new String[]{"probing_cane"}, 45, 19, false),
      new FacebookEmoji(0x1F517, new String[]{"link"}, 30, 17, false),
      new FacebookEmoji(new int[] { 0x26D3, 0xFE0F }, new String[]{"chains"}, 56, 57, false),
      new FacebookEmoji(0x1FA9D, new String[]{"hook"}, 54, 36, false),
      new FacebookEmoji(0x1F9F0, new String[]{"toolbox"}, 53, 52, false),
      new FacebookEmoji(0x1F9F2, new String[]{"magnet"}, 53, 54, false),
      new FacebookEmoji(0x1FA9C, new String[]{"ladder"}, 54, 35, false),
      new FacebookEmoji(new int[] { 0x2697, 0xFE0F }, new String[]{"alembic"}, 56, 38, false),
      new FacebookEmoji(0x1F9EA, new String[]{"test_tube"}, 53, 46, false),
      new FacebookEmoji(0x1F9EB, new String[]{"petri_dish"}, 53, 47, false),
      new FacebookEmoji(0x1F9EC, new String[]{"dna"}, 53, 48, false),
      new FacebookEmoji(0x1F52C, new String[]{"microscope"}, 30, 38, false),
      new FacebookEmoji(0x1F52D, new String[]{"telescope"}, 30, 39, false),
      new FacebookEmoji(0x1F4E1, new String[]{"satellite_antenna"}, 29, 24, false),
      new FacebookEmoji(0x1F489, new String[]{"syringe"}, 27, 1, false),
      new FacebookEmoji(0x1FA78, new String[]{"drop_of_blood"}, 54, 13, false),
      new FacebookEmoji(0x1F48A, new String[]{"pill"}, 27, 2, false),
      new FacebookEmoji(0x1FA79, new String[]{"adhesive_bandage"}, 54, 14, false),
      new FacebookEmoji(0x1FA7A, new String[]{"stethoscope"}, 54, 15, false),
      new FacebookEmoji(0x1F6AA, new String[]{"door"}, 37, 6, false),
      new FacebookEmoji(0x1F6D7, new String[]{"elevator"}, 38, 45, false),
      new FacebookEmoji(0x1FA9E, new String[]{"mirror"}, 54, 37, false),
      new FacebookEmoji(0x1FA9F, new String[]{"window"}, 54, 38, false),
      new FacebookEmoji(new int[] { 0x1F6CF, 0xFE0F }, new String[]{"bed"}, 38, 39, false),
      new FacebookEmoji(new int[] { 0x1F6CB, 0xFE0F }, new String[]{"couch_and_lamp"}, 38, 30, false),
      new FacebookEmoji(0x1FA91, new String[]{"chair"}, 54, 24, false),
      new FacebookEmoji(0x1F6BD, new String[]{"toilet"}, 38, 16, false),
      new FacebookEmoji(0x1FAA0, new String[]{"plunger"}, 54, 39, false),
      new FacebookEmoji(0x1F6BF, new String[]{"shower"}, 38, 18, false),
      new FacebookEmoji(0x1F6C1, new String[]{"bathtub"}, 38, 25, false),
      new FacebookEmoji(0x1FAA4, new String[]{"mouse_trap"}, 54, 43, false),
      new FacebookEmoji(0x1FA92, new String[]{"razor"}, 54, 25, false),
      new FacebookEmoji(0x1F9F4, new String[]{"lotion_bottle"}, 53, 56, false),
      new FacebookEmoji(0x1F9F7, new String[]{"safety_pin"}, 53, 59, false),
      new FacebookEmoji(0x1F9F9, new String[]{"broom"}, 54, 1, false),
      new FacebookEmoji(0x1F9FA, new String[]{"basket"}, 54, 2, false),
      new FacebookEmoji(0x1F9FB, new String[]{"roll_of_paper"}, 54, 3, false),
      new FacebookEmoji(0x1FAA3, new String[]{"bucket"}, 54, 42, false),
      new FacebookEmoji(0x1F9FC, new String[]{"soap"}, 54, 4, false),
      new FacebookEmoji(0x1FAA5, new String[]{"toothbrush"}, 54, 44, false),
      new FacebookEmoji(0x1F9FD, new String[]{"sponge"}, 54, 5, false),
      new FacebookEmoji(0x1F9EF, new String[]{"fire_extinguisher"}, 53, 51, false),
      new FacebookEmoji(0x1F6D2, new String[]{"shopping_trolley"}, 38, 42, false),
      new FacebookEmoji(0x1F6AC, new String[]{"smoking"}, 37, 8, false),
      new FacebookEmoji(new int[] { 0x26B0, 0xFE0F }, new String[]{"coffin"}, 56, 47, false),
      new FacebookEmoji(0x1FAA6, new String[]{"headstone"}, 54, 45, false),
      new FacebookEmoji(new int[] { 0x26B1, 0xFE0F }, new String[]{"funeral_urn"}, 56, 48, false),
      new FacebookEmoji(0x1F5FF, new String[]{"moyai"}, 32, 51, false),
      new FacebookEmoji(0x1FAA7, new String[]{"placard"}, 54, 46, false)
    };
  }

  private ObjectsCategoryChunk0() {
    // No instances.
  }
}
